sudo: required

services:
  - docker

before_install:
  - docker build -t comet_csc .

script:
  - docker run -v $TRAVIS_BUILD_DIR:/root/analysis comet_csc /bin/bash -c "source activate open-ml && cd /root/analysis && snakemake run_manual run_ml"