name: open-ml
dependencies:
- numpy=1.10.4=py35_1
- openblas=0.2.14=4
- openssl=1.0.2g=0
- pandas=0.17.0
- numexpr=2.4
- matplotlib=1.4.3
- scikit-learn=0.17.0
- pip=8.1.1
- pip:
  - snakemake==3.6.1
  - runipy==0.1.5
  - ipyparallel==5.0.1
  - ipython-genutils==0.1.0
  - itsdangerous==0.24
  - jupyterhub==0.5.0
  - jupyter==1.0.0
